
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common']

 name: Add docker apt repository key.
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    dest: //etc/apt/keyrings/docker.gpg
    mode: '0755'
    force: true

- name: Add docker apt repository.
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu/"
    state: present
    update_cache: true

- name: Install a list of packages
  ansible.builtin.apt:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io','docker-buildx-plugin','docker-compose-plugin']
     
- name: Adding Jenkins and Docker to Ubuntu Grp
  user:
      name: ['ubuntu', 'jenkins']
      groups: docker
      append: yes

- name: Stop docker service
  service:
    name: docker
    state: started
    enabled: yes

    
    

    